blueprint:
  name: Zigbee2MQTT - Loratap SS600ZB / Tuya TS0043 Zigbee Wireless Switch
  description: Automate your Loratap SS600ZB / Tuya TS0043 Zigbee Wireless Switch via Zigbee2MQTT.
  domain: automation
  input:
    switch:
      name: Loratap SS600ZB / Tuya TS0043 Zigbee Wireless Switch
      description: Loratap SS600ZB / Tuya TS0043 Zigbee Wireless Switch to use
      selector:
        entity:
          integration: mqtt
          domain: sensor
    button_one_short_press:
      name: Single Press - Button 1
      description: Action to run on button 1 - single press
      default: []
      selector:
        action: {}
    button_one_double_press:
      name: Double Press - Button 1
      description: Action to run on button 1 - double press
      default: []
      selector:
        action: {}
    button_one_long_press:
      name: Long Press - Button 1
      description: Action to run on button 1 - long press
      default: []
      selector:
        action: {}
    button_two_short_press:
      name: Single Press - Button 2
      description: Action to run on button 2 - single press
      default: []
      selector:
        action: {}
    button_two_double_press:
      name: Double Press - Button 2
      description: Action to run on button 2 - double press
      default: []
      selector:
        action: {}
    button_two_long_press:
      name: Long Press - Button 2
      description: Action to run on button 2 - long press
      default: []
      selector:
        action: {}
    button_three_short_press:
      name: Single Press - Button 3
      description: Action to run on button 3 - single press
      default: []
      selector:
        action: {}
    button_three_double_press:
      name: Double Press - Button 3
      description: Action to run on button 3 - double press
      default: []
      selector:
        action: {}
    button_three_long_press:
      name: Long Press - Button 3
      description: Action to run on button 3 - long press
      default: []
      selector:
        action: {}
  source_url: https://github.com/AramidX/ha-blueprint/blob/8e259f8e40ab1218f06ea1ce1d1444f67b4cd62f/blueprints/tuya/loratap_ss600zb_wireless_switch_z2m.yaml
mode: restart
max_exceeded: silent
trigger:
  - platform: state
    entity_id: !input "switch"
action:
  - variables:
      command: "{{ trigger.to_state.state }}"
  - choose:
      - conditions:
          - "{{ command == '1_single' }}"
        sequence: !input "button_one_short_press"
      - conditions:
          - "{{ command == '2_single' }}"
        sequence: !input "button_two_short_press"
      - conditions:
          - "{{ command == '3_single' }}"
        sequence: !input "button_three_short_press"
      - conditions:
          - "{{ command == '1_double' }}"
        sequence: !input "button_one_double_press"
      - conditions:
          - "{{ command == '2_double' }}"
        sequence: !input "button_two_double_press"
      - conditions:
          - "{{ command == '3_double' }}"
        sequence: !input "button_three_double_press"
      - conditions:
          - "{{ command == '1_hold' }}"
        sequence: !input "button_one_long_press"
      - conditions:
          - "{{ command == '2_hold' }}"
        sequence: !input "button_two_long_press"
      - conditions:
          - "{{ command == '3_hold' }}"
        sequence: !input "button_three_long_press"
