sensor:
  - name: "Zigbee2mqtt Networkmap"
    state_topic: "zigbee2mqtt/bridge/response/networkmap"
    value_template: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
    json_attributes_topic: "zigbee2mqtt/bridge/response/networkmap"
    json_attributes_template: "{{ value_json.data.value | tojson }}"
