sp_dc: ""
sp_key: ""

coinmarketcap_curl: ""

todolist_authorization: ""
todolist_project: ""

git_exporter_user: ""
git_exporter_pass: ""

todoist_token: ""

dev_track_xiaomi_hub: ""

tg_group: ""
tg_me: ""
tg_api: ""

living_remote: ""
bedroom_remote: ""

17login: ""
17pass: ""

mouse: ""

openweather_all: ""

aqoo: ""

db_link: ""

poly_key: ""
poly_id: ""

platerecognizer: ""

eth_wallet: ""

weather_long: ""
weather_lat: ""

phuket_rent: ""

home_long: ""
home_lat: ""
